### ISSUE TITLE
improve logging in CollectionAndDataObjectListAndSearchAOImpl

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [DICE-UNC/jargon#135]
Hi,

This is a low priority request for CollectionAndDataObjectListAndSearchAOImpl.listDataObjectsUnderPathWithPermissionsUsingGenQuery():

The L1279 in CollectionAndDataObjectListAndSearchAOImpl.java has:

```
            log.debug("got result set:{}}, resultSet");
```
- One minor typo is it has an extra closing curly brace
- And it would make more sense to print the result set instead of printing object class + pointer

This would make the call more useful for actual debugging / troubleshooting - thanks a lot in advance.

Cheers,
Vlad

Link: https://github.com/DICE-UNC/jargon/blob/master/jargon-core/src/main/java/org/irods/jargon/core/pub/CollectionAndDataObjectListAndSearchAOImpl.java#L1279

**Comment by michael-conway** [comment]
thanks vladimir.

BTW I welcome pull requests!
