### ISSUE TITLE
Support for PAM in cyberduck

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon#136]
```Java

  @Override
    public void login(final PasswordStore keychain, final LoginCallback prompt, final CancelCallback cancel,
                      final Cache<Path> cache) throws BackgroundException {
        try {
            final String region = this.getRegion();
            final String resource = this.getResource();
            final IRODSAccount account = IRODSAccount.instance(host.getHostname(), host.getPort(),
                    host.getCredentials().getUsername(), host.getCredentials().getPassword(),
                    this.workdir().getAbsolute(), region, resource);

            final IRODSAccessObjectFactory factory = client.getIRODSAccessObjectFactory();
            final AuthResponse auth = factory.authenticateIRODSAccount(account);
            if(auth.isSuccessful()) {
                filesystem = factory.getIRODSFileSystemAO(auth.getAuthenticatedIRODSAccount());
            }
            else {
                throw new LoginFailureException(MessageFormat.format(LocaleFactory.localizedString(
                        "Login {0} with username and password", "Credentials"), host.getHostname()));
            }
        }
        catch(JargonException e) {
            throw new IRODSExceptionMappingService().map(e);
        }
    }


```

**Comment by michael-conway** [comment]
IRODSAccount has signatures in instance() that accept an AuthScheme

e.g.

```Java



/**
	 * Creates an object to hold iRODS account information. All parameters need
	 * to be initialized to use this initializer. Note that this instance method
	 * will set the auth scheme
	 * 
	 * @param host
	 *            the iRODS server domain name
	 * @param port
	 *            the port on the iRODS server
	 * @param userName
	 *            the user name
	 * @param password
	 *            the password
	 * @param homeDirectory
	 *            home directory on the iRODS
	 * @param zone
	 *            the IRODS zone
	 * @param defaultStorageResource
	 *            default storage resource
	 * @param authenticationScheme
	 *            authenticationScheme to use
	 */
	public static IRODSAccount instance(final String host, final int port,
			final String userName, final String password,
			final String homeDirectory, final String zone,
			final String defaultStorageResource,
			final AuthScheme authenticationScheme) throws JargonException {



```

So we'd need to add an add'l item in the config for AuthScheme as   empty|STANDARD|PAM

We can default to Standard if not specified.  Extracting that and setting the AuthScheme enum value in IRODSAccount to STANDARD or PAM is all that's required.

Note that PAM uses SSL, so it will require a (hopefully real) SSL cert that the JVM understands, otherwise you'll have to import the certs manually using java keytool.

**Comment by michael-conway** [comment]
for this cyberduck code, we can add a flag for pam to the configuration, including adding a PAM:userName in the host.getCredentials().getUserName() Cyberduck API code.

We just need to say, in the ch.cyberduck.core.irods.IRODSSession code 

```Java
@Override
    public void login(final PasswordStore keychain, final LoginCallback prompt, final CancelCallback cancel,
                      final Cache<Path> cache) throws BackgroundException {
        try {
            final String region = this.getRegion();
            final String resource = this.getResource();
            final AuthScheme authScheme = AuthScheme.findTypeByString(someMethodToReturnSTANDARDorPAMfromConfig);

            final IRODSAccount account = IRODSAccount.instance(host.getHostname(), host.getPort(),
                    host.getCredentials().getUsername(), host.getCredentials().getPassword(),
                    this.workdir().getAbsolute(), region, resource, authScheme);

            final IRODSAccessObjectFactory factory = client.getIRODSAccessObjectFactory();
            final AuthResponse auth = factory.authenticateIRODSAccount(account);
            if(auth.isSuccessful()) {
                filesystem = factory.getIRODSFileSystemAO(auth.getAuthenticatedIRODSAccount());
            }
            else {
                throw new LoginFailureException(MessageFormat.format(LocaleFactory.localizedString(
                        "Login {0} with username and password", "Credentials"), host.getHostname()));
            }
        }
        catch(JargonException e) {
            throw new IRODSExceptionMappingService().map(e);
        }
    }


```

to call this signature in IRODSAccount in Jargon, and PAM should be enabled

``` Java

public static IRODSAccount instance(final String host, final int port,
			final String userName, final String password,
			final String homeDirectory, final String zone,
			final String defaultStorageResource,
			final AuthScheme authenticationScheme) throws JargonException {


```

**Comment by dkocher** [comment]
Is it possibly to hook up your own trust manager (`javax.net.ssl.X509TrustManager`) or socket factory for verifying SSL certificates?

**Comment by michael-conway** [comment]
Yes I think this is really needed, especially for self signed certs.

We're in the middle of redoing the SSL so we can implement transport 
security for the protocol itself (above what's done for pam).

I'll add that to the Transport security milestone, which is in the 
issue4 branch.  That won't be in the next couple of weeks, though, I'm 
quite certain.

Cheers
MC

**Comment by dkocher** [comment]
This will be integrated from [this](https://g.iterate.ch/projects/ITERATE/repos/cyberduck/compare/commits?targetBranch=refs%2Fheads%2Fmaster&sourceBranch=refs%2Fheads%2Ffeature%2FsupportAuthSchemeIrods&targetRepoId=32) pull request. You will need to prefix the non default auth scheme in the username field of the login prompt delimited with a `:`. For example `PAM:iterate`.

**Comment by dkocher** [comment]
I get a `Unknown iRODS exception code recieved:-2101000.` when testing with PAM against `data.iplantcollaborative.org`. Is this expected to work?

**Comment by michael-conway** [comment]
make sure the iPlant cert is in your local keystore.  It looks like an SSL handshake error

**Comment by dkocher** [comment]
The error is returned in reply to `sslStartInp_PI` from `irodsCommands.irodsFunction(sslStartInp)` in `org.irods.jargon.core.connection.PAMAuth` before the SSL handshake.

**Comment by dkocher** [comment]
What is the progress on the issue4 branch?

**Comment by michael-conway** [comment]
Ahh...OK, let's talk to iPlant today, what server are you going 
against?  If this is their 'test' 4.1.5/6 they may not have the server 
side SSL conf in place.  PAM itself does work through SSL outside of 
your testing.

**Comment by michael-conway** [comment]
It is still going to take some time and testing. It would not be 
relevant to this set of changes.  I think it may be 3 weeks before we 
roll that out.
