### ISSUE TITLE
Carification on proper way to delete a collection

### ISSUE THREAD

**Issue by deardooley** [DICE-UNC/jargon#139]
What is the proper way to delete a collection with one or more data objects in it? I have tried the following options:
- `IRODSFile#delete` : successfully deletes the folder (or rather moves it to the trash), but leads to potential corruption and the -528002 and -511020 errors within a few requests.
- `IRODSFile#deleteWithForceOption` successfully deletes data objects and empty collections. Throws error that the collection is not empty when attempting to use on a non-empty collection.
- `IRODSFileSystemAO#directoryDeleteForce`: successfully deletes the folder (or rather moves it to the trash), but leads to potential corruption and the -528002 and -511020 errors within a few requests.
- `IRODSFileSystemAO#directoryDeleteNoForce` successfully deletes data objects and empty collections. Throws error that the collection is not empty when attempting to use on a non-empty collection.

Is there perhaps a **cleanup** call I need to make after deleting a collection without the force option to prevent the -511020 from occurring? 

Is there a clean way to recursively delete a collection and its contents or do I need to write the recursion myself? 

What are the non-force delete methods doing in their recursive calls?

**Comment by michael-conway** [comment]
Hey Rion trying to catch up.

I think you are running into various 'trash' errors, I'll review my own unit tests and make sure we have one for each case for starters.  Are you on 4.1.3?

**Comment by deardooley** [comment]
I have run into trash errors on 3.3 and 4.0.3, though the errors are usually thrown while I’m trying to clean up rather than because I didn’t. They are also not predictable. Given a serial, ordered execution the file system will get corrupted about 1 in 4 consecutive runs. If I blow away the container between runs, it falls to about 1 in 8 or so. 

I don’t have a  4.1.3 image. Our v4 test images are forks of the Docker builds posted on the [IRODS website](http://irods.org/post/irods-on-docker-update/#.VcFj-5NViko) with modifications for easier setup of bootstrap data and use in test scenarios. We do have a 4.1.x cluster set up in Arizona that we include as one of the IRODS systems in our test matrix, but I’ll need to look further into the differences there. As of right now, all of our regression tests break when run against v4.  I believe I submitted tickets about the biggest issues such as changes in the order of operations for permission and existence checks, additional status without a clear description of their hierarchy or lack thereof, clarification on federation behavior, resource resolution, and existence of data DNS.


—
Rion
