### ISSUE TITLE
SSL cert check bypass option

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon#155]
add an option to bypass SSL cert checks, see http://stackoverflow.com/questions/19723415/java-overriding-function-to-disable-ssl-certificate-check

**Comment by dkocher** [comment]
We wouldn't want to disable SSL certificate checks but have the option to inject our own instance of `X509TrustManager` and `X509KeyManager` that allows us to compare with system and user trust settings.

**Comment by michael-conway** [comment]
I think that would be possible to stick in IRODSSession, let me take a look.

**Comment by dkocher** [comment]
See also #136.

**Comment by michael-conway** [comment]
added controllable by jargon property

# bypass ssl certificate checks, not recommended for production deployments
bypass.ssl.cert.checks=false

IRODSSession can now take an injected trust manager via its setter method
