### ISSUE TITLE
Collection not found on iRODS 4.1.x + Mysql (plugin)

### ISSUE THREAD

**Issue by gilbert-n** [DICE-UNC/jargon#160]
I have been playing with iRODS 4.1.x + MySQL installation. I am right now using Jargon 4.0.2.3-RELEASE. ( For some reasons, what I am going to describe here does not happen when I switch to the same iRODS version installation + postgreSQL)

Issue description:

I user Jargon to create new collections using IRODSFile objects as follows:
- Start with parentCollPath
- Create childCollPath: parentCollectionPath + "/" + childName; (A typical childColPath looks like: /tempZone/test_folder1/testFolder2/testFolder3/childName.
- Use IRODSFileFactory to create IRODSFile objects:
  IRODSFileFactory factory = fileSystem.getIRODSFileFactory(account);
  IRODSFile irodsFile = factory.instanceIRODSFile(childCollPath);
  if(!irodsFile.exist()) irodsFile.makedirs();

The collections are created successfully. I verified using both icommands and idrop-web.

Now the problem becomes when I am trying to recreate/ retrieve the newly created collections as IRODSFile objects from their absolute paths:

IRODSFileFactory factory = fileSystem.getIRODSFileFactory(account);
IRODSFile irodsFile = factory.instanceIRODSFile(childCollPath);

Now if I try something like irodsFile.exist() I get a mixture of responses. On occasions I get TRUE, and other times, I get FALSE even when I know for sure that there files exists.

Here is a small part of the logs I get when running factory.instanceIRODSFile(childCollPath) which suggest that maybe there might be some issues in the CollectionIteratorAOImpl implementation:
(I used [childCollPath] to replace the real path)

[btpool0-0] INFO org.irods.jargon.core.pub.io.IRODSFileImpl - setting file name, given path = [childCollPath]
[btpool0-0] INFO org.irods.jargon.core.pub.io.IRODSFileImpl - detected local separator = /
[btpool0-0] INFO org.irods.jargon.core.pub.io.IRODSFileImpl - file name was set as: [childName]
[btpool0-0] INFO org.irods.jargon.core.pub.IRODSFileSystemAOImpl - isFileExists()
[btpool0-0] INFO org.irods.jargon.core.pub.IRODSFileSystemAOImpl - checking existence of: [childCollPath]
[btpool0-0] INFO org.irods.jargon.core.pub.IRODSFileSystemAOImpl - getObjStat(final String irodsAbsolutePath)
[btpool0-0] INFO org.irods.jargon.core.pub.CollectionAndDataObjectListAndSearchAOImpl - retrieveObjectStatForPathWithHeuristicPathGuessing()
[btpool0-0] INFO org.irods.jargon.core.pub.CollectionAndDataObjectListAndSearchAOImpl - got a file not found, try to heuristically produce an objstat
[btpool0-0] INFO org.irods.jargon.core.pub.CollectionIteratorAOImpl - handleNoObjStatUnderRootOrHomeByLookingForPublicAndHome()
[btpool0-0] INFO org.irods.jargon.core.pub.CollectionIteratorAOImpl - really is a not found for file:/[childCollPath]
[btpool0-0] INFO org.irods.jargon.core.pub.IRODSFileSystemAOImpl - file not found, will treat as not exists

Could it be that the problem lies in one of the retrieveObjectStatForPathWithHeuristicPathGuessing() algorithms or some other processes invoked by factory.instanceIRODSFile(childCollPath)? 

(I did check the release notes from jargon 4.0.2.4-RELEASE to see if anything related was among the changes)

**Comment by michael-conway** [comment]
I would suspect Gen query, honestly.  We can do some tests with the
consortium configuration that run mysql icats.
