### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by kosarko** [DICE-UNC/jargon#162]
Seems that dependency cog-jglobus 1.8.0 is no longer available via maven. It's not possible to compile unless you already have `~/.m2/repository/org/globus/jglobus/cog-jglobus/1.8.0/` in your local maven repository

**Comment by michael-conway** [comment]
Yes globus is difficult.  I'm considering just yanking it from Jargon.  
I get this occasionally. locally it would be a manual install of the jar 
to a local maven repo, as I don't distribute it.
