### ISSUE TITLE
Irods Jargon-core seems to compile and run without jglobus or com.claymore dependencies just fine

### ISSUE THREAD

**Issue by markehammons** [DICE-UNC/jargon#176]
Hi, 

I've been trying to depend on jargon for my project, but these two dependencies have been a pain for me. I have to import [renci's repository](http://ci-dev.renci.org/nexus/content/repositories/public) as a resolver for my project to get either of these dependencies and the md5/sha1 checksums for jglobus are recorded improperly on the above resolver so I have to disable checksum checking to get it. Compiling jargon-core with these dependencies removed seems to cause no problems, and ditto for using jargon-core without them (at least for what I've been using jargon-core for for now). Is it possible to remove these dependencies from jargon-core officially? Both are kind of a pain to deal with, and jglobus makes me very concerned since I have to turn off any basic dependency safety to make use of it with jargon.

**Comment by michael-conway** [comment]
removed for now, may need to add a globus plugin back when it comes to implementing globus auth
