### ISSUE TITLE
IRODSAccount fails with whitespace in default path

### ISSUE THREAD

**Issue by dkocher** [DICE-UNC/jargon#189]
When the `homeDirectory` of has a whitespace `#toURI` will fail with an unrecoverable `URISyntaxException`.

**Comment by dkocher** [comment]
I don't see a patch applied fixing this issue.

**Comment by michael-conway** [comment]
I will double check but I recall fixing the issue to utilize url encoding,
there should also be a unit test referencing 189 in the test name.  I will
check!
