### ISSUE TITLE
SHA256 property in ObjStat

### ISSUE THREAD

**Issue by dkocher** [DICE-UNC/jargon#193]
It looks like the checksum property in ObjStat can be in the format `sha2:47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU= `. The prefix should be removed and the content Base64 decoded. For MD5 checksums there is no such prefix it seems and we can just parse this checksum and guess its digest implementation based on the string length. See also https://trac.cyberduck.io/ticket/9662

**Comment by michael-conway** [comment]
Hey David, that prefix is an iRODS artifact, as the checksum type is set 
by policy.  So as new checksum algos are adopted, they can be 
represented.  It's ugly, yes, but they are avoiding schema changes to 
the catalog at this point.  Lots of our users have moved away from MD5 
as insecure, and it's becoming less prevalent.


MC

**Comment by dkocher** [comment]
Can you confirm that checksums are now always Base64 encoded? That was not previously the case with MD5 it seems.

**Comment by carsten-jahn** [comment]
Hi David, yes they are always base64 encoded. I found an 'official' document here: https://docs.irods.org/master/manual/tips_and_tricks/

**Comment by michael-conway** [comment]
Sha are base64, md5 are printed as hex strings.  The MD5 in the iRODS protocol is an ancient code relic.  If we want to, I can add an option to get the MD5 also as base64. Internally, though, the hex format is what is used in the protocol operations.

like this...

```java
public static String digestByteArrayToString(final byte[] digestAsByteArray) {

		if (digestAsByteArray == null) {
			throw new IllegalArgumentException(
					"unknown format, not recognized as an MD5 checksum in a byte array");
		}

		StringBuilder sb = new StringBuilder();

		for (byte element : digestAsByteArray) {
			sb.append(String.format("%02x", element));
		}

		return sb.toString();
	}


```
