### ISSUE TITLE
add checksum support to Jargon streaming API

### ISSUE THREAD

**Issue by carsten-jahn** [DICE-UNC/jargon#194]
In https://github.com/DICE-UNC/irods-cloud-browser/issues/182 , we found that:

`jargon.properties` setting `transfer.computeandvalidate.checksum=true` has no effect if the Java code uses the Jargon streaming API. It would make sense to respect the setting in this code path as well. This would transparently enable the affected client (e.g. iRODS cloud browser) to transmit files along with a client-computed checksum to iRODS.

**Comment by michael-conway** [comment]
checksum computed when jargon properties set as such.
