### ISSUE TITLE
PAM auth failure when password includes semicolon

### ISSUE THREAD

**Issue by trel** [DICE-UNC/jargon#195]
From https://groups.google.com/forum/#!topic/iROD-Chat/2_1zE3cNzXw

> We've had a user who tried to log in to our iRODS (4.1.8) based service using:
> 
> iCommands in Linux
> Cloudbrowser (1.0.0)
> Cyberduck V4.9.0 (Windows 8.1)
> 
> Login was successful using the iCommands but failed using both the Cloudbrowser and Cyberduck.
> 
> It seems likely that this is a problem with the PAM handling libraries within JARGON.
> 
> Some probing in cyberduck shows that it will not tolerate the semicolon ';' in passwords, but appears fine with other symbols. Cyberduck provides more helpful debugging information than the CloudBrowser.
> 
> Steps to reproduce the error:
> for an iRODS connection within CyberDuck use "PAM:" followed by a username that does not need to be real.
> enter any password containing ';' (quotes not needed)
> 
> The result is an "Error" window with the message: Unknown iRODS exception code received:-158000.
> 
> Subsequent attempts to connect do not request the user name or password again, but bring up the same error message. You can reset it by editing the bookmark to remove the username entirely.
> 
> Repeating the above with non "PAM:" user names, does not fail in the same way.

**Comment by michael-conway** [comment]
replicated with 

```Java

@Test
	public final void testPAMAuthSemicolonBug195() throws Exception {
		if (!testingPropertiesHelper.isTestPAM(testingProperties)) {
			return;
		}

		String pamUser = "someuserBug195";
		String pamPassword = "howAbout;Here";

		IRODSAccount irodsAccount = testingPropertiesHelper
				.buildIRODSAccountForIRODSUserFromTestPropertiesForGivenUser(
						testingProperties, pamUser, pamPassword);

		irodsAccount.setAuthenticationScheme(AuthScheme.PAM);
		EnvironmentalInfoAO environmentalInfoAO = irodsFileSystem
				.getIRODSAccessObjectFactory().getEnvironmentalInfoAO(
						irodsAccount);
		environmentalInfoAO.getIRODSServerCurrentTime();

		AuthResponse authResponse = environmentalInfoAO.getIRODSProtocol()
				.getAuthResponse();
		Assert.assertNotNull("no authenticating account",
				authResponse.getAuthenticatingIRODSAccount());
		Assert.assertEquals("did not set authenticating account to PAM type",
				AuthScheme.PAM, authResponse

				.getAuthenticatingIRODSAccount().getAuthenticationScheme());

		irodsFileSystem.closeAndEatExceptions();

	}



```

**Comment by dkocher** [comment]
See also #202.

**Comment by michael-conway** [comment]
rodsLog


```
an  3 11:12:42 pid:2755 NOTICE: Agent process 3061 started for puser=someuserBug195 and cuser=someuserBug195 from 172.16.250.1
Jan  3 11:12:46 pid:3061 ERROR: [-]     iRODS/server/api/src/rsAuthPluginRequest.cpp:85:rsAuthPluginRequest :  status [SYS_BAD_INPUT]  errno [] -- message []
        [-]     libpam.cpp:400:pam_auth_agent_request :  status [SYS_BAD_INPUT]  errno [] -- message []
                [-]     iRODS/lib/core/src/irods_kvp_string_parser.cpp:181:parse_escaped_kvp_string :  status [SYS_BAD_INPUT]  errno [] -- message [no unescaped _assoc token encountered before unescaped delimiter when parsing kvp]

Jan  3 11:12:46 pid:3061 ERROR: [-]     iRODS/server/core/src/rsApiHandler.cpp:470:readAndProcClientMsg :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message []
        [-]     iRODS/lib/core/src/sockComm.cpp:199:readMsgHeader :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']
                [-]     libssl.cpp:577:ssl_read_msg_header :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [read 0 expected 4]

Jan  3 11:12:46 pid:3061 NOTICE: Agent exiting with status = -4000
Jan  3 11:12:46 pid:2755 NOTICE: Agent process 3061 exited with status 24576
(END)

```

will check w/consortium folks

**Comment by michael-conway** [comment]
iRODS/server/api/src/rsAuthPluginRequest.cpp uses ; as a KVP struct delimiter, so added '\\' escape syntax to pam password, verified via unit test. (see commit to follow)

**Comment by michael-conway** [comment]
fixed and tested in commit to follow
