### ISSUE TITLE
"Catalog SQL error" in jargon-core when using Oracle

### ISSUE THREAD

**Issue by marc-flesch** [DICE-UNC/jargon#196]
Hallo Michael,

I don't know if you recall me? We met in person a year ago @iRODS2015 meeting in UNC-Renci. I'm the guy with the kidney stone issue :) I gave a talk about an iRODS integration project in cooperation with Bayer.

Now one of our customers (Merck Germany) is trying to run iRODS on an ORACLE installation and is facing some issues within jargon-core.jar API. Maybe you can help them figuring out what might be the source of the problem.

Let me try to summarize what they have tested so far:
# Setup 1:
- iRODS 4.1.8 on PostgreSQL using jargon-core version 4.0.2.5-RELEASE 
  => which works fine.
# Setup 2:
- iRODS 4.1.8 on Oracle 12c using jargon-core version 4.0.2.5-RELEASE  
  => fails with the attached stack trace. 

See the line 144ff of the attached server.txt file:
[server.txt](https://github.com/DICE-UNC/jargon/files/467747/server.txt)

and the iRODS log file:
[rodsLog.2016.08.16.txt](https://github.com/DICE-UNC/jargon/files/467768/rodsLog.2016.08.16.txt)

The failing API call seems to be:

```
boolean IRODSFileSystemAO.isFileWriteable(IRODSFile irodsFile) throws FileNotFoundException,
JargonException;
```

**Any idea why this works on PostgreSQL but fails on Oracle?**

If you need further clarification on how to reproduce the issue you can contact either the Merck technical lead: Praveen MK praveen.mk@external.merckgroup.com or me Marc Flesch marc@genedata.com.

Best,
Marc.

**Comment by michael-conway** [comment]
I am able to reproduce the 806000, which is occurring in the execution of specific query (this is prepared sql executed via an alias) to get group permissions.

This is likely an iRODS server side bug, and I will coordinate with the server folks

**Comment by michael-conway** [comment]
ben has a fix to the specific query, 

try the following procedure
```
iadmin rsq listUserACLForDataObjViaGroup

```

then 

```
iadmin asq "SELECT R_USER_MAIN.user_name, R_USER_MAIN.user_id, R_OBJT_ACCESS.access_type_id, R_USER_MAIN.user_type_name, R_USER_MAIN.zone_name, R_COLL_MAIN.coll_name, R_DATA_MAIN.data_name, USER_GROUP_MAIN.user_name, R_DATA_MAIN.data_name, R_COLL_MAIN.coll_name FROM R_USER_MAIN USER_GROUP_MAIN JOIN R_USER_GROUP JOIN R_USER_MAIN ON R_USER_GROUP.user_id = R_USER_MAIN.user_id ON USER_GROUP_MAIN.user_id = R_USER_GROUP.group_user_id JOIN R_OBJT_ACCESS ON R_USER_GROUP.group_user_id = R_OBJT_ACCESS.user_id JOIN R_DATA_MAIN JOIN R_COLL_MAIN ON R_DATA_MAIN.coll_id = R_COLL_MAIN.coll_id ON R_OBJT_ACCESS.object_id = R_DATA_MAIN.data_id WHERE  R_COLL_MAIN.coll_name = ? AND R_DATA_MAIN.data_name = ? AND R_USER_MAIN.user_name = ? ORDER BY R_COLL_MAIN.coll_name, R_DATA_MAIN.data_name, R_USER_MAIN.user_name, R_OBJT_ACCESS.access_type_id DESC" listUserACLForDataObjViaGroup

```

**Comment by michael-conway** [comment]
an example patch script to test is in jargon-core per https://github.com/DICE-UNC/jargon/blob/master/jargon-core/specific_query_patch-bug196.sh

please try this and see if it fixes the issue

**Comment by reinhard-doelz** [comment]
https://github.com/DICE-UNC/jargon/blob/master/jargon-core/specific_query_patch-bug196.sh removes listUserACLForDataObjViaGroup and adds listUserACLForCollectionViaGroup - this isn't working. Actually, both queries have an AS that should be removed. See also, https://github.com/irods/irods/issues/3433. 
Having both queries without AS works in Oracle 12c. 
See also, http://stackoverflow.com/questions/8451195/is-the-as-keyword-required-in-oracle-to-define-an-alias

**Comment by michael-conway** [comment]
OK sorry about that, that's my error.  Will revisit that with Ben, but the
issue is that the queries loaded into iRODS for Oracle have some sql
differences that need to be accounted for.  I'll see about just getting a
patch from the consortium of the same style.

**Comment by reinhard-doelz** [comment]
Thank you for the fast response. 
There's another Oracle issue that I see, in the predefined queries for ilsLACollections and ilsLADataObjects as you mentioned the compatibility...

The issue is that the construct DESC LIMIT :2 OFFSET :3 is not ok in Oracle 12c https://oracle-base.com/articles/12c/row-limiting-clause-for-top-n-queries-12cr1 . It rather should read OFFSET ... ROWS FETCH NEXT ... ROWS ONLY but it doesn't seem to work as of yet as I tried.

**Comment by michael-conway** [comment]
Thanks, I think I'll just yank that attempt at a 'patch' of specific query and instead that should come from the Consortium folks.  I am working with Ben on this side to get iRODS+Oracle into CI as there are, as we found, more than one specific query that has Oracle issues.

**Comment by michael-conway** [comment]
updated to new global issue to cover general iRODS testing.  Will close this one and continue with a more systematic solution at https://github.com/DICE-UNC/jargon/issues/219
