### ISSUE TITLE
IndexOutOfBoundsException in PackingIrodsOutputStream

### ISSUE THREAD

**Issue by dkocher** [DICE-UNC/jargon#200]
With `byteBufferSizeMax` set to `32768`.

```
java.lang.IndexOutOfBoundsException
    at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:151)
    at org.irods.jargon.core.pub.io.PackingIrodsOutputStream.write(PackingIrodsOutputStream.java:99)
```

**Comment by michael-conway** [comment]
added test...passes...will try changing other params. Set jargon props putBufferSize to 32768.  Will verify that.

Is there a magic number on the input file size that triggers this?

**Comment by michael-conway** [comment]
able to reproduce...added a functional test with a lazy walk...

**Comment by michael-conway** [comment]
Will close for now here.  Will do further testing under REST and WebDav, but the failing scenario and all of the functional tests now pass (lazy walk of file size and various buffer params).
