### ISSUE TITLE
iRODS CS_NEG_REQUIRE + PAM authentication

### ISSUE THREAD

**Issue by ghost** [DICE-UNC/jargon#215]
I'm trying to authenticate users through Jargon in iRODS. The authentication mechanism is PAM. My `core.re` file is set to `CS_NEG_REQUIRE` and I am able to login into iRODS using `iinit` successfully, but the same doesn't happen when I try logging in using Jargon.

Here is the code I'm using to implement the login via Jargon:

```
ClientServerNegotiationPolicy policy = new ClientServerNegotiationPolicy();
policy.setSslNegotiationPolicy(SslNegotiationPolicy.CS_NEG_REQ);

IRODSAccount acct = IRODSAccount.instance("icat", 1247, "arthur", "arthur", "", "tempZone", "");
acct.setAuthenticationScheme(AuthScheme.PAM);
acct.setClientServerNegotiationPolicy(policy);

IRODSFileSystem irodsFileSystem = IRODSFileSystem.instance();
IRODSAccessObjectFactory factory = irodsFileSystem.getIRODSAccessObjectFactory();
factory.authenticateIRODSAccount(acct);
factory.closeSessionAndEatExceptions(acct);
```

When I run the code above, I get the following result:

```
[main] INFO  connection.IRODSSimpleProtocolManager  - creating simple protocol manager
[main] INFO  connection.IRODSSession  - setting system prop for TLS...
[main] INFO  connection.IRODSSession  - checkInitTrustManager()
[main] INFO  pub.IRODSFileSystem  - IRODSfileSystem is initialized
[main] INFO  pub.IRODSAccessObjectFactoryImpl  - authenticateIRODSAccount()
[main] WARN  connection.IRODSSession  - closing session that is already closed, silently ignore
[main] INFO  connection.AbstractIRODSMidLevelProtocolFactory  - instance() method...calling connection life cycle
[main] INFO  connection.AbstractIRODSMidLevelProtocolFactory  - create connection....
[main] INFO  connection.IRODSTCPConnectionFactoryImpl  - instance()
[main] INFO  connection.AbstractConnection  - AbstractConnection()
[main] INFO  connection.AbstractConnection  - using override negotiation policy from IRODSAccount:ClientServerNegotiationPolicy [sslNegotiationPolicy=CS_NEG_REQ]
[main] INFO  connection.AbstractConnection  - opening irods socket
[main] INFO  connection.AbstractIRODSMidLevelProtocolFactory  - ...have connection, now authenticate given the auth scheme in the iRODS account...
[main] INFO  connection.AbstractIRODSMidLevelProtocolFactory  - authenticate()
[main] INFO  connection.AbstractIRODSMidLevelProtocolFactory  - get auth mechanism
[main] INFO  connection.AuthenticationFactoryImpl  - instanceAuthMechanism()
[main] INFO  connection.AuthenticationFactoryImpl  - authScheme:PAM
[main] INFO  connection.AuthenticationFactoryImpl  - using PAM auth
[main] INFO  connection.AbstractIRODSMidLevelProtocolFactory  - authenticate...
[main] INFO  connection.AuthMechanism  - sendStartupPacket()
[main] INFO  connection.AuthMechanism  - clientServerNegotiationHook()
[main] INFO  connection.AuthMechanism  - negotiation is required
[main] INFO  connection.AuthMechanism  - clientServerNegotiation()
```

Even though I had manually set the negotiation policy, it complained saying that negotiation is required, which I do not understand why.

If I remove the policy negotiation part from the code and set my `core.re` file in iRODS to be `CS_NEG_DONT_CARE`, the authentication works (as expected), but it is not gonna use SSL for authentication (am I right?).

Any ideas on how to make it work when iRODS is set to always require SSL? Am I missing something?

Thanks in advance!

**Comment by michael-conway** [comment]
SSL is used for PAM even if no negotiation occurs.  I think we need to test this against the jargon 'master' branch, where the SSL negotiation support now exists.  I can create an 'alpha' jargon release for you today and you can test it.  Are you pulling the last release, rather than the master or snapshot?  I think that's the actual root cause.  FWIW PAM + SSL unit tests against master are all successful.

**Comment by ajguerra** [comment]
I'm using Jargon 4.0.2.6-RELEASE. I would be more than happy to test it if possible.

**Comment by ajguerra** [comment]
I just cloned the repository and build myself a 4.1.10.0-SNAPSHOT of Jargon. Same output =/

**Comment by michael-conway** [comment]
thx will prepare a test this morning

**Comment by michael-conway** [comment]
But just a question...it sounds like the auth failed?  The log above shows what -should- happen, in that negotiation -should- be required, that's not an error message, that's just saying that the client/server will negotiate SSL.  

So to clarify..

1.  Does the PAM authentication fail?  What does the log say on the failure?
2.  Is there, further down in your log, exceptions in the client/server negotiation beyond an invalid authentication?

So the log message may be confusing, it's really saying that the client wants to negotiate with the server is all.  it will do this after the PAM authentication is successful.  Jargon previously, and still does, use SSL when doing the PAM authentication.  At the time it was done, the SSL tunneling was turned on to send the PAM credentials, and then turned off while we awaited approval of general SSL use (export restrictions and the like).  

What happens in negotiation is that after authentication is successful by any mechanism, the client and server send their preferences to each other, and based on those preferences SSL is turned on, and other stuff is exchanged to set up secure transfer.  In the case of PAM, it should see that SSL is already tunneled and just continue on its way.  

Hence my question, if we ignore that log message as just saying "Hey, I'm going to negotiate SSL now" and see whether the PAM auth is failing, or something about SSL negotiation is failing, it'll help narrow this down.

**Comment by ajguerra** [comment]
I am not so sure if the PAM authentication is failing (see logs below) or it is something else. It looks to me that Jargon (or perhaps my code) is failing before it even tries to authenticate. 

This is all I get from the iRODS logs:

```
Jan  5 09:31:04 pid:2890 NOTICE: Agent process 26855 started for puser=arthur and cuser=arthur from 10.26.103.58
Jan  5 09:31:04 pid:26855 ERROR: [-]    iRODS/server/core/src/rodsAgent.cpp:207:main :  status [SYS_HEADER_READ_LEN_ERR]  errno [Resource temporarily unavailable] -- message []
        [-]     iRODS/server/core/src/irods_server_negotiation.cpp:178:client_server_negotiation_for_server :  status [SYS_HEADER_READ_LEN_ERR]  errno [Resource temporarily unavailable] -- message []
                [-]     iRODS/lib/core/src/irods_client_negotiation.cpp:477:read_client_server_negotiation_message :  status [SYS_HEADER_READ_LEN_ERR]  errno [Resource temporarily unavailable] -- message [read message header failed]
                        [-]     iRODS/lib/core/src/sockComm.cpp:199:readMsgHeader :  status [SYS_HEADER_READ_LEN_ERR]  errno [Resource temporarily unavailable] -- message [failed to call 'read header']
                                [-]     libtcp.cpp:240:tcp_read_msg_header :  status [SYS_HEADER_READ_LEN_ERR]  errno [Resource temporarily unavailable] -- message [read 0 expected 4]

Jan  5 09:31:04 pid:26855 ERROR: [-]    iRODS/server/core/src/rodsAgent.cpp:211:main :  status [SYS_HEADER_READ_LEN_ERR]  errno [Resource temporarily unavailable] -- message []
        [-]     iRODS/server/core/src/irods_server_negotiation.cpp:178:client_server_negotiation_for_server :  status [SYS_HEADER_READ_LEN_ERR]  errno [Resource temporarily unavailable] -- message []
                [-]     iRODS/lib/core/src/irods_client_negotiation.cpp:477:read_client_server_negotiation_message :  status [SYS_HEADER_READ_LEN_ERR]  errno [Resource temporarily unavailable] -- message [read message header failed]
                        [-]     iRODS/lib/core/src/sockComm.cpp:199:readMsgHeader :  status [SYS_HEADER_READ_LEN_ERR]  errno [Resource temporarily unavailable] -- message [failed to call 'read header']
                                [-]     libtcp.cpp:240:tcp_read_msg_header :  status [SYS_HEADER_READ_LEN_ERR]  errno [Resource temporarily unavailable] -- message [read 0 expected 4]

Jan  5 09:31:04 pid:26855 NOTICE: Agent exiting with status = -4011
Jan  5 09:31:05 pid:2890 NOTICE: Agent process 26855 exited with status 256
```

I'm guessing from the log entries that my code and iRODS are failing during some sort of handshake before starting the authentication process itself.

I have already double checked the iRODS PAM documentation trying to see I've made a mistake during configuration, but it looks ok to me. 

Also, I'm able to authenticate properly using `iinit` no matter what the iRODS configuration is for PAM: `CS_NEG_DONT_CARE` or `CS_NEG_REQUIRE`. However, Jargon only works when I set the grid to `CS_NEG_DONT_CARE`.

**Comment by michael-conway** [comment]
I think I replicated and fixed it, will have a push once the tests complete!

**Comment by michael-conway** [comment]
Note that a secondary issue, especially with self-signed certificates, is to ensure that a self signed public key has been added to the Java keystore via the keytool command, otherwise you can get SSL handshake errors.  If PAM auth succeeds in the dont care mode, the cert is probably ok.

**Comment by ajguerra** [comment]
Agreed. I'm using self-signed certificates, but I already added the PK to my JVM keystore. That was actually the first thing I thought that was causing the problem, but unfortunately it wasn't.

**Comment by michael-conway** [comment]
will move this over to pending....I think this is fixed and will have a chance to look at this once the RC1 is out

**Comment by ajguerra** [comment]
All right. As soon as RC1 is release I'll git it a try! Thanks!

**Comment by michael-conway** [comment]
Ok that should be monday or tuesday, I'm just reviewing the final issues

**Comment by ajguerra** [comment]
ok

**Comment by ajguerra** [comment]
Hi Mike, sorry to bother you again, but is there anything else I could do to help you with this issue? Maybe run a test or change any iRODS configuration.

Thanks!

**Comment by michael-conway** [comment]
Sure, just pm me today michael.c.conway@gmail.com

**Comment by michael-conway** [comment]
...pending field test with current 4.1.10.0-SNAPSHOT

**Comment by ajguerra** [comment]
Mike,

I was playing with Jargon 4.1.10.0-RC2 and I noticed that it now seems to encapsulate every auth message into SSL. 

The authentication works just fine when iRODS is set up to authenticate via PAM. However, when I run the same code against a Standard-Auth iRODS it fails saying, "Remote host closed connection during handshake".

To make RC2 work against an iRODS with Standard auth I had to create the `chain.pem`, `server.key` and `dhparams.pem` files on the server side, although I don't use them. 

Is that the correct behaviour?

Thx!

**Comment by michael-conway** [comment]
It depends on the client-server negotiation params set up on the client and
the server.

jargon should default to 'don't care' which defers to the server.  Can you
tell me what the negotiation status is in the core.re?

I think there is an outstanding issue we saw in CI with neg refuse on the
server still triggering the negotiation sequence we were working through.

Cheers
MC

**Comment by ajguerra** [comment]
Negotiation status in the core.re file stands for `CS_NEG_DONT_CARE`. I haven't changed this file. My env was set following the standard iRODS installation.

**Comment by michael-conway** [comment]
Yes.  The neg dont care in the core.re is what is used by the negotiation
process.  If jargon is dont care and irods is dont care then ssl is used.
That's the algo.

it needs to be refuse in core.re.

The negotiation stance in that irods_environment file on the server
controls negotiation between that irods server and another federated
server.  This tripped me up as well!

**Comment by jasoncoposky** [comment]
for the iRODS service account all settings in irods_environment.json are used for both federation as well as any server to server redirection.  for this reason, it is recommended that all servers have identical SSL settings.

**Comment by ajguerra** [comment]
Got it! Thanks @michael-conway and @jasoncoposky

**Comment by michael-conway** [comment]
this seems to be a config issue...retesting with this release to ensure that it can be closed out

**Comment by michael-conway** [comment]
CS_NEG_REQUIRE and PAM auth working as expected.
