### ISSUE TITLE
PAM authentication failure with -319000

### ISSUE THREAD

**Issue by dkocher** [DICE-UNC/jargon#224]
Since the 4.1.10 builds PAM connections seem to fail with `-319000`. See also https://trac.cyberduck.io/ticket/9826

The assumptions in the linked thread do not apply here. The threading issues discussed in the linked [thread](https://groups.google.com/forum/#!topic/iROD-Chat/F1HaH4BGEcs) are not the cause; in Cyberduck a single connection is not accessed from different threads.

**Comment by michael-conway** [comment]
Sure, that's not what we see out in other field testing, so if this is the
iplant grid, we should test in place.  I am proposing with Tony and Dennis
to get together this afternoon to do some initial testing.

**Comment by dkocher** [comment]
@michael-conway Great, looking forward to the results.

**Comment by dkocher** [comment]
The reason for this failure was a regression that included a `PAM:` prefix in the username when trying to authenticate.

**Comment by trel** [comment]
"PAM:" was not being removed before sending the password through to Jargon.
  https://trac.cyberduck.io/ticket/9872

Fixed in https://trac.cyberduck.io/changeset/38419

**Comment by michael-conway** [comment]
Thx will try and look this morning.  I've been off site for the last week,
sorry to be slow on this one.

**Comment by trel** [comment]
Confirmed here to work with renciZone via PAM.

This is my .cyberduckprofile file:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Protocol</key>
        <string>irods</string>
        <key>Vendor</key>
        <string>renciZone</string>
        <key>Description</key>
        <string>RENCI iRODS</string>
        <key>Hostname Configurable</key>
        <false/>
        <key>Port Configurable</key>
        <false/>
        <key>Default Hostname</key>
        <string>icat.edc.renci.org</string>
        <key>Region</key>
        <string>renciZone:rootResc</string>
        <key>Default Port</key>
        <string>1247</string>
        <key>Username Placeholder</key>
        <string>username</string>
        <key>Password Placeholder</key>
        <string>password</string>
        <key>Authorization</key>
        <string>PAM</string>
    </dict>
</plist>
```

Note the new (to me):
```
        <key>Authorization</key>
        <string>PAM</string>
```

Then when logging in, used regular username, without the leading `PAM:` from earlier documentation.

**Comment by dkocher** [comment]
Yes, we added support for specifying the authentication scheme (PAM) in the connection profile for the upcoming 5.4 release to remove the `PAM:` prefix requirement. @trel I assume you are running the current snapshot build of Cyberduck.

**Comment by trel** [comment]
Yes, just switched to the snapshot and About Box reports 6.0.0.    Thank you.

The documentation on the wiki will need be updated:
 - remove "PAM:" prefix note
 - replace with Auth scheme stanza
