### ISSUE TITLE
Add object pooling protocol manager

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon#225]
For webdav, rest performance, implement an irods protocol manager using commons pool

https://commons.apache.org/proper/commons-pool/api-2.4.2/index.html

This will feed into upgrades of webdav, rest, cloudbrowser once tested

**Comment by dkocher** [comment]
Concerning Cyberduck or Mountain Duck this is of no interest to us as we want to manage our own pool (also implemented using commons-pool btw) where the size can be configured by the user or some application logic.

**Comment by michael-conway** [comment]
It wont impact that.. This is typically wired in via spring so it only
would be there if configured, typically on a back end server that has
connection per request sorts of patterns.  our own webdav, for example,
will open a new connection for each stateless web request.
