### ISSUE TITLE
puretls 1.1 & cog-jglobus 1.8.0 missing

### ISSUE THREAD

**Issue by ajguerra** [DICE-UNC/jargon#226]
Hi @michael-conway,

I was setting up a new dev environment from scratch and during the build I notice two packages were missing:  __cog-jglobus__ (1.8.0) and __puretls__ (1.1).

Then, I took a look at another dev environment I´ve been working with for a few months and those two packages exist inside my local maven repo (under the `.m2` directory).

Looking for answers to this problem, I found this [issue](https://github.com/DICE-UNC/idrop/issues/16) on the iDROP Github that reports the same problem. There I found another repo (`http://ci-dev.renci.org/nexus/content/repositories/public`), I added it as another repository in my `pom.xml` and maven could finally find those two missing dependencies.

I was wondering if only `https://raw.github.com/DICE-UNC/DICE-Maven/master/releases` should be able to resolve those two dependencies or should I really add this third repo to my project?

**Comment by michael-conway** [comment]
We'd not done a lot with Globus, it needs to be added to auth methods.
That ci-dev repository is rather old and is pre-consortium legacy.  For now
it's OK, but we can add a better resolution for this 4.2 compatible Jargon.
We're going to move to that rather quickly.

The Globus jars were very difficult to find out on any Maven repo, and a
bit of investigation on whether they've made them more available is worth
another look. My hope is to start addressing the larger question of jargon
repos getting onto maven central, that's a thing we keep talking about.

**Comment by ajguerra** [comment]
What I do not understand is how I've got these libraries in my `.m2` directory. Maven somehow managed to resolve those dependencies and find these `jars` at some point, but it is not working anymore.

For now, I'll leave this legacy repo to avoid breaking any Jargon dependencies in my code.

Thanks!

**Comment by bpow** [comment]
The JGlobus project is now community maintained and is [on github](https://github.com/jglobus/JGlobus). Newer versions of JGlobus are also available on maven central (under org.jglobus), but I'm not sure about the CoG portions of the library.

**Comment by michael-conway** [comment]
Ok at will add to 4.2.1 support release, also a pr is welcome any time!

**Comment by bpow** [comment]
#251 is the relevant pull request. Things compile cleanly on my end with this set of patches, but I don't know that I can adequately test the GSI part of things, so please double-check.

**Comment by michael-conway** [comment]
That's awesome!  I'll check it out.  On a related note, the Jargon unit
tests do depend on a local 'scratch' iRODS, typically run in a VM.  It's
really pretty straight forward and there are docs/scripts in Jargon that
can help configure the unit tests if you'd like to try that.
