### ISSUE TITLE
Lantency issues

### ISSUE THREAD

**Issue by ngmenyen** [DICE-UNC/jargon#234]
Hi all,

I noticed there is a difference in latency when comparing [4.0.2.6-RELEASE](https://github.com/DICE-UNC/jargon/releases/tag/4.0.2.6-RELEASE) and [4.1.10.0-RC1 Release Candidate](https://github.com/DICE-UNC/jargon/releases/tag/4.1.10.0-RC1) using the same method to display the content of a collection. Later releases also have this problem.

The delay I got when using the later version was five times longer than using the same method from the earlier version. Approximately 1200 ms from 4.1.10-RC and 250 ms from 4.0.2.6

Is there a way to reduce this time?

Best regards,
Ng Men Yen

**Comment by dkocher** [comment]
See also #212.

**Comment by michael-conway** [comment]
Sure, happy to look at with you...

The first thing I'd ask is whether you've added SSL support?  A big change
was SSL negotiation.

Second, is the version of iRODS the very same?  Same database,etc?

Let's line up all our versions and check on whether SSL is now involved
first.  The collection listings are essentially SQL queries run through
GenQuery, we can try some benchmark tests.

Cheers
MC

**Comment by ngmenyen** [comment]
Thanks for the fast reply!

We are not using SSL and our core.re file has CS_NEG_REFUSE in it. 

We are using iRODS 4.1.10 for both jargon versions. Aside from jargon version, everything is the same for both.

Regards,
Ng Men Yen

**Comment by michael-conway** [comment]
I want to add some timing information and if you want to test off a
snapshot we see where the latency occurs.

**Comment by ngmenyen** [comment]
Sure I want to test it! I would be glad to!

**Comment by ngmenyen** [comment]
Hi, Mike.

Do you have any updates on this topic?

Cheers
