### ISSUE TITLE
Jargon optimizations for large files

### ISSUE THREAD

**Issue by sviscapi** [DICE-UNC/jargon#286]
Hi,

We are trying to read a large file (1TB) from iRods using an input stream.
We are facing some performance issues, the transfer is very slow (more than 6 hours).
We have identified three possible actions :
- disabling the computations of checksums (it does not improve the reading a lot).
- increasing the number of threads (setMaxParallelThreads(), 4 seems to be a good value)
- buffer tuning by setting the size(s) using the Jargon properties.

We could use some help to identify which Jargon buffer(s) could be configured to reduce the duration of the reading :
properties.setGetBufferSize();
properties.setPutBufferSize();
properties.setInternalInputStreamBufferSize(); <-- could it be a good candidate ?
properties.setInternalOutputStreamBufferSize();
properties.setLocalFileInputStreamBufferSize(); <-- could it be a good candidate ?
properties.setLocalFileOutputStreamBufferSize();
properties.setParallelCopyBufferSize(); <-- could it be a good candidate ?
properties.setSendInputStreamBufferSize();

Last but not least, is the size of these buffers evaluated as bytes ?

Best regards,

**Comment by michael-conway** [comment]
Input streams are just terribly slow, are you trying to transfer the file,
or do you need that stream access?

DataTransferOperations has put/get semantics that can do parallel transfer,
streaming does NOT use the parallel transfer algo.

This might be what you want...

https://github.com/DICE-UNC/jargon/blob/master/jargon-core/src/main/java/org/irods/jargon/core/pub/DataTransferOperations.java#L175-L181


If you MUST use streaming you can use the 'packing' streams which do some
buffer optimization

https://github.com/DICE-UNC/jargon/blob/master/jargon-core/src/main/java/org/irods/jargon/core/pub/io/PackingIrodsInputStream.java
https://github.com/DICE-UNC/jargon/blob/master/jargon-core/src/main/java/org/irods/jargon/core/pub/io/PackingIrodsOutputStream.java

So iput semantics and iget semantics are supported in Jargon, the stream
stuff is a wholly separate code path on client and in iRODS.

Let me know if that makes sense, happy to help you tune things up.

**Comment by infodavide** [comment]
Thanks for the explanation. 
So, you mean that setting the size(s) of the buffer(s) is useless?

**Comment by michael-conway** [comment]
Not necessarily, we can still tweak. The packing streams will certainly
help.

The real first question is whether it has to be data presented as a stream
versus transferred with put or get semantics

**Comment by infodavide** [comment]
The current process reads the file (tar or similar) using the input stream to extract the content on the fly. This is used to avoid allocating to much disk space.

**Comment by michael-conway** [comment]
Sure we'll try the packing stream first. A big issue w streams is that each
read() or write() of a byte buffer is a complete round trip irods protocol
operation, that's why the packing streams help by caching until enough data
is there to amortize the expense.

After that if it's not sufficient it might be worthwhile to chat with Jason
and Terrell to see what the next moves might be.

**Comment by infodavide** [comment]
0k, we will try asap and let you know. 

Thanks Michael

**Comment by infodavide** [comment]
Hi,

We have improved the process by using a packing input stream and setup the buffer sizes to 4194304.
The estimation is around 2,5 hours for 1TB on our 1st environment but we have to check the gain on the pre-production one.

Thanks

**Comment by michael-conway** [comment]
Ok some comparison to put/get may be useful. I am entertaining a way to
fool the iget code path to act as an input stream but that would only work
acting a a single buffer put. Maybe post a more general topic on irods chat
so Jason and crew can see!

**Comment by michael-conway** [comment]
closing for now...open a new issue if required!
