### ISSUE TITLE
Physical path

### ISSUE THREAD

**Issue by infodavide** [DICE-UNC/jargon#287]
Hello, 

Is there a way to get the absolute path of the physical location of a file? 

Best regards

**Comment by michael-conway** [comment]
yes,

e.g.

https://github.com/DICE-UNC/jargon/blob/master/jargon-core/src/main/java/org/irods/jargon/core/pub/DataObjectAO.java#L490


and

https://github.com/DICE-UNC/jargon/blob/master/jargon-core/src/main/java/org/irods/jargon/core/pub/CollectionAndDataObjectListAndSearchAO.java#L513

**Comment by michael-conway** [comment]
also..
https://github.com/DICE-UNC/jargon/blob/master/jargon-core/src/main/java/org/irods/jargon/core/pub/DataObjectAO.java#L1027

**Comment by infodavide** [comment]
Thanks a lot Michael
