### ISSUE TITLE
Add multipart support/pluggable transport

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon#297]
see https://github.com/irods/irods_api_plugin_multipart

Add a plugin for transport into Jargon and implement unipart and multipart protocols at https://github.com/irods/irods_api_plugin_multipart

**Comment by korydraughn** [comment]
iRODS now supports parallel transfer over port 1247 and Jargon has native support for it.

Closing as there's nothing actionable for this issue.
