### ISSUE TITLE
ResourceAOImpl.listResourceNames() returns an empty list from Oracle

### ISSUE THREAD

**Issue by jaksat0202** [DICE-UNC/jargon#308]
To get a list of top resources the IRODSGenQueryBuilder builds this query:
     " SELECT RESC_NAME WHERE RESC_PARENT = '' "
which works  for Postgresql as R_RESC_MAIN.RESC_PARENT contains a string of two single quote characters for top resources.

But in Oracle RESC_PARENT contains actually NULL for top resources so the above Query returns always 0 rows (it should say WHERE RESC_PARENT IS NULL).

Diagnosis: Postgresql stores two single quotes as a string whereas Oracle converts two single quotes (en empty string) to NULL.

Comment: It does not help to update RESC_PARENT to actually contain two single quotes as it results in an INVALID_LEXICAL_CAST inside the iRods core: [failed to cast ''].

Environment:
iRods: 4.2.3-1
Oracle: 12c

**Comment by michael-conway** [comment]
hey @trel this may be irods-involved...

**Comment by trel** [comment]
this still causing problems?   is jargon generating the incorrect SQL?

I see an inconsistency within the database with postgresql, regardless...

```
$ ilsresc
demoResc:unixfilesystem
pt:passthru
└── ufs1:unixfilesystem

$ iquest "select RESC_NAME where RESC_PARENT = ''"
RESC_NAME = pt
------------------------------------------------------------

$ iquest "select RESC_NAME where RESC_PARENT IS NULL"
RESC_NAME = bundleResc
------------------------------------------------------------
RESC_NAME = demoResc
------------------------------------------------------------
```

**Comment by michael-conway** [comment]
Hey Terrell Jargon doesn't generate any SQL it's all GenQuery commands...we
can take a look at this one if we have a test env. I'm not equipped to
stand up an Oracle iCAT

**Comment by trel** [comment]
fair enough.

**Comment by michael-conway** [comment]
I think what we can do is do a 'special' specific query exit for this operation? In other words, detect that it's an Oracle iCAT and go SQL via specific query so it can handle NULLs. I'll try to look into this but it would be an overhead of an iRODS issue. What do you guys think?

**Comment by michael-conway** [comment]
So what I'd propose would be a well named and documented specific query
alias (listTopResources for example). If jargon encounters this alias it
will substitute and do a direct sql call. I'll try to do that early this
week so we can test it.

**Comment by jaksat0202** [comment]
I'm not so fluent with the internal syntax of GenQuery but it should be easy to test against a real database.

**Comment by michael-conway** [comment]
NB I've pushed a fix that doesn't (I think) require specific query. It seems to work locally on Postgres but we need to test on Oracle. What I can do is push a new build of iDrop and we can try this live against the target iRODS? How does this sound. Then if it satisfies the case we'll close this issue.

**Comment by jaksat0202** [comment]
Sounds good. I'd be happy to test it.

**Comment by michael-conway** [comment]
ok I will work on this iDrop push and ping back to this issue
