### ISSUE TITLE
publish to public repository

### ISSUE THREAD

**Issue by idot** [DICE-UNC/jargon#33]
It would be great to have your artifacts published to a public repository like maven central.
I only find beta libraries from 2007 there.

http://mvnrepository.com/search.html?query=jargon

**Comment by pietvandongen** [comment]
Is there an update to this? I'd like to be able to use a public artifact repository as well.

**Comment by michael-conway** [comment]
Right now we just don't have time

**Comment by pietvandongen** [comment]
@michael-conway That's too bad, let me know if and how I can help!
