### ISSUE TITLE
Drag-and-Drop in iDrop, check if paths resolved in move

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon#334]
folder xxx
...yyy
...zzz

drag of yyy onto zzz does not produce zzz/yyy, complains that folder already exists, verify the path resolution on a move in jargon -> idrop

**Comment by korydraughn** [comment]
Is this a Jargon issue or iDrop issue?

**Comment by trel** [comment]
Don't know - close it as resolved/invalid.
