### ISSUE TITLE
Using microservice msiDataObjGet doesn't keep the number of the required replica

### ISSUE THREAD

**Issue by JEREM-M** [DICE-UNC/jargon#345]
We have a rule invoked by jargon which use the microservice msiDataObjGet and we try to get a specific replica.

**Our scenario** 

capsREF:replication
├── vanneREF-1:passthru
│.......└── elemREF-1:unix file system
└── vanneREF-2:passthru
........└── elemREF-2:unix file system

Rule
msiDataObjGet(*rodsPath, "localPath=*localFilePath++++replNum=*currentReplNum++++forceFlag=", *getStatus);

with
rodsPath=/SAS/AIP/2421/6889/7316/ark-12148-br2d22g.version9.release0.tar
localFilePath=/partage/transfert/storage/output/acc01-access/4d4b5b50-f968-11e9-85dd-0001a4ab132d/ark-12148-br2d22g.version9.release0.tar
currentReplNum= 0

The required replica (number 0) is on the elemREF-1 resource.
By playing with read/write priority of the passthru resources, we noticed that it's always the priority replica which is fetched and not the one asked.
The replNum parameter don't have any impact on the call.

Doing the same thing without using jargon, produce the correct result so it seems IRODS is not the source of problem

### The issue on IRODS side :
https://github.com/irods/irods/issues/4565

**Comment by tledoux** [comment]
Indeed, looking at

https://github.com/DICE-UNC/jargon/blob/fd078e2abad6d5a6fc43fb97b6f7deafabb37cb5/jargon-core/src/main/java/org/irods/jargon/core/pub/RuleProcessingAOImpl.java#L800-L831

we see that only the `localPath`, the `rescName` and the `forceFlag` keywords are copied from the rule to the client side action. In order for the `replNum` to be taken into account it should be copied as well.
