### ISSUE TITLE
iRODS 4 Dynamic Policy Enforcement Points to be triggered

### ISSUE THREAD

**Issue by ilarik** [DICE-UNC/jargon#349]
Hi,

As discussed quickly yesterday I would like to make the following request for enhancement: the iRODS 4.x dynamic policy enforcement points such as `pep_api_data_obj_put_post` to be triggered always after a PUT is completed using Jargon-based clients (so that the application built on the library wouldn't need to worry about triggering the PEP).

I have a case here with a user having a data ingest pipeline built on top of Jargon (at least version [jargon-core-4.2.2.0-RELEASE] - that was the case some time ago) from which we are receiving objects but no longer can trigger the post processing hook after moving to the dynamic PEP away from `acPostProcForPut` as instructed by Jason.

Are these known to work with (or at least some later versions of) Jargon or are these something that are still not possible to trigger using Jargon? If the support is existing, I would still like to propose to make their invocation "non-voluntary" from the client API :)

**Comment by trel** [comment]
I think this is because the Jargon client calls are using open-write-close?  rather than put?

**Comment by michael-conway** [comment]
open/write/close should have the proper open flags set, it is sensitive to
that. I'll be looking at the test case.

**Comment by michael-conway** [comment]
This is likely about the openflags used. In IRODSFileImpl in the close...
```
if (openFlags == OpenFlags.WRITE || openFlags == OpenFlags.WRITE_FAIL_IF_EXISTS
				|| openFlags == OpenFlags.WRITE_TRUNCATE) {
			log.info("closing with putOpr");
			irodsFileSystemAO.fileClose(getFileDescriptor(), true);
		} else {
			irodsFileSystemAO.fileClose(getFileDescriptor(), false);

		}

```

This sets the oprType on the close that will cause the PEP to fire. My unit tests show the PEP does properly fire. Can we look at the code in question and inspect how the open flags are set?

@trel  @ilarik

**Comment by trel** [comment]
The flag check above *does* make the static pep `acPostProcForPut` trigger.

The new dynamic peps only fire for the operation they are invoking, so an `open/write/close` sequence of operations will never trigger `pep_api_data_obj_put_post`...  and this is correct behavior.

More policy needs to be instrumented on the server-side to trigger on the operations of interest.

I think this can be closed as wontfix/invalid.
