### ISSUE TITLE
add connection naming to startup pack

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon#352]
in startup pack message buffer, look for rcConnect l 1100 startupPack.option 

Think about a sig that allows 'naming' of a connection

**Comment by michael-conway** [comment]
import contextlib
import time
import os
from irods.session import iRODSSession

@contextlib.contextmanager
def session(name_):
    try:
        env_file = os.environ['IRODS_ENVIRONMENT_FILE']
    except KeyError:
        env_file = os.path.expanduser('~/.irods/irods_environment.json')
    session = iRODSSession(irods_env_file=env_file, name = name_)   # <<< specify the app name here
    try:
        yield session
    finally:
        session.cleanup()
        print "cleanup"

if __name__ == '__main__':
    with session("myApp") as s:
        s.collections.get('/tempZone/home/alissa')
        time.sleep(15.0)

**Comment by korydraughn** [comment]
Resolved by #423 and #430.
