### ISSUE TITLE
Cannot target custom rule engine plugin instance when executing rules

### ISSUE THREAD

**Issue by korydraughn** [DICE-UNC/jargon#358]
Currently, Jargon only supports the Native and Python rule engine plugins. Because there are newer rule engine plugins available, Jargon needs to allow specifying rule engine plugin instances outside of the Native and Python instances.

This would allow execution of commands with non-traditional syntax.

For example, the [logical quotas](https://github.com/irods/irods_rule_engine_plugin_logical_quotas) rule engine plugin supports the following syntax:
```javascript
{
    "operation": "logical_quotas_start_monitoring_collection",
    "collection": "/tempZone/home/rods"
}
INPUT null
OUTPUT null
```

**Comment by michael-conway** [comment]
picking up...will add to the test docker framework for further work...

**Comment by michael-conway** [comment]
hey @korydraughn, check this signature out...

https://github.com/DICE-UNC/jargon/blob/master/jargon-core/src/main/java/org/irods/jargon/core/pub/RuleProcessingAO.java#L287-L288


```
/**
	 * See above comment for details. This variant adds an
	 * <code>IrodsRuleInvocationTypeEnum</code> value that can cue Jargon on which
	 * rule engine (python, irods) the rule is bound for. In the above method, the
	 * invocation type defaults to auto and Jargon will try and do some simple
	 * checks to guess what type of rule is being processed.
	 *
	 * @param irodsRuleAsString
	 *            {@code String} with the rule body, as well as input and output
	 *            parameters.
	 * @param inputParameterOverrides
	 *            {@code List} of {@link IRODSRuleParameter} that overrides the
	 *            parameters derived from the rule bodies.
	 *
	 * @param ruleInvocationConfiguration
	 *            {@link RuleInvocationConfiguration} that represents the type of
	 *            rule engine the user wishes this rule to be run on. With multiple
	 *            rule engines iRODS needs this information to properly process the
	 *            rule. If set to AUTO_DETECT Jargon will try and guess (but may not
	 *            be too smart at first).
	 * @return {@link IRODSRuleExecResult} that represents the results of processing
	 *         the rule.
	 * @throws JargonRuleException
	 *             if an exception occurred in rule translation.
	 * @throws JargonException
	 *             if iRODS processing resulted in an error.
	 */
	IRODSRuleExecResult executeRule(String irodsRuleAsString, List<IRODSRuleParameter> inputParameterOverrides,
			final RuleInvocationConfiguration ruleInvocationConfiguration) throws JargonRuleException, JargonException;


```

That accepts a RuleInvocationConfiguration....
https://github.com/DICE-UNC/jargon/blob/ac906a192e01925b2863788ef4287760f31dd8d6/jargon-core/src/main/java/org/irods/jargon/core/rule/RuleInvocationConfiguration.java#L33-L39

If you specify a string in that field it should pass it on to the proper rule engine. I'm looking thru this and need to better understand the syntactical implications...eg how override parameters might be affected, but it SHOULD just accept the string you give it as the target...

The rule engine chooser sees that string and uses it as an override...if that's what's going on than any signature that uses this RuleInvocationConfiguration should honor the custom name

https://github.com/DICE-UNC/jargon/blob/ac906a192e01925b2863788ef4287760f31dd8d6/jargon-core/src/main/java/org/irods/jargon/core/rule/RuleEngineInstanceChooser.java#L79-L81

**Comment by michael-conway** [comment]
hey @korydraughn or @trel is there a 4.3 docker image type deal available? I can make a specific test here, but I do think using the RuleInvocationConfiguration it -should- work as expected. The specific rule engine instance supplied there overrides any automatic detection. Whether it has any downstream side-effects is what I need to test out.

**Comment by trel** [comment]
This is what we've built so far to easily run code-in-development in containers...
  https://github.com/irods/irods_development_environment

Happy to demo quick if that's helpful.

**Comment by michael-conway** [comment]
that looks like a pretty good start...try out using that alternate invocation signature and I'll dig into the 4.3 docker image

**Comment by korydraughn** [comment]
I'll try using that and let you know what happens.

**Comment by korydraughn** [comment]
Turns out I tried that before and it didn't work.  I just verified that it still fails.  This is the message I receive on failure:
```java
Exception in thread "main" org.irods.jargon.core.rule.UnknownRuleTypeException: cannot determine rule type
	at org.irods.jargon.core.rule.RuleTypeEvaluator.guessRuleLanguageType(RuleTypeEvaluator.java:77)
	at org.irods.jargon.core.rule.IrodsRuleFactory.instanceIrodsRule(IrodsRuleFactory.java:97)
	at org.irods.jargon.core.pub.RuleProcessingAOImpl.executeRule(RuleProcessingAOImpl.java:365)
	at com.irods.sandbox.JargonTests.main(JargonTests.java:72)
```

I verified that the plugin was installed and functioning properly too.  Do I need to update my version of Jargon?

**Comment by trel** [comment]
can't hurt - what version generated that error?

**Comment by michael-conway** [comment]
No and that's helpful Kory...I can do more on this fact, and will be
looking to add the 4.3 irods so I can test directly thanks. It's downstream
of the rule engine selection so it's a side effect. I'll work on it.

**Comment by korydraughn** [comment]
Weirdly enough, I tried again using `IrodsRuleInvocationTypeEnum.IRODS`, but I passed it the JSON hard link data and it worked. I'm confused by this. It fails if I try to use `ctx.setRuleEngineSpecifier("irods_rule_engine_plugin-hard_links-instance")`.

**Comment by korydraughn** [comment]
The failing code is:
```java
sb.append("{\n");
sb.append("    \"operation\": \"hard_links_create\",\n");
sb.append("    \"logical_path\":\"/tempZone/home/kory/foo\",\n");
sb.append("    \"replica_number\": \"0\",\n");
sb.append("    \"link_name\":\"/tempZone/home/kory/foo.jargon\"\n");
sb.append("}\n");

RuleProcessingAO rpao = aof.getRuleProcessingAO(acct);
RuleInvocationConfiguration ctx = new RuleInvocationConfiguration();
ctx.setRuleEngineSpecifier("irods_rule_engine_plugin-hard_links-instance");
		
rpao.executeRule(sb.toString(), null, ctx);
```

**Comment by trel** [comment]
is it possible the iRODS REPF took it to the `irods_rule_language-instance`... and then fellthrough to the `hard_links-instance`?

**Comment by korydraughn** [comment]
I think that is what is happening.  No errors appear in my log.  This is the message I see:
```bash
"log_message": "Rule Engine Plugin returned [0]."
```
This message appears when no REP instance is specified.

**Comment by korydraughn** [comment]
This is the code that works:
```java
sb.append("{\n");
sb.append("    \"operation\": \"hard_links_create\",\n");
sb.append("    \"logical_path\":\"/tempZone/home/kory/foo\",\n");
sb.append("    \"replica_number\": \"0\",\n");
sb.append("    \"link_name\":\"/tempZone/home/kory/foo.jargon\"\n");
sb.append("}\n");

RuleProcessingAO rpao = aof.getRuleProcessingAO(acct);
RuleInvocationConfiguration ctx = new RuleInvocationConfiguration();

// This line is the only difference between the two.
ctx.setIrodsRuleInvocationTypeEnum(IrodsRuleInvocationTypeEnum.IRODS);
		
rpao.executeRule(sb.toString(), null, ctx);
```

**Comment by korydraughn** [comment]
@trel The hard link instance is the first REP in my config.

I'm going to swap it with the NREP and see what happens.

**Comment by korydraughn** [comment]
It still worked, even after making the hard links REP second in the list.  No errors produced.  It means that the server is not seeing any REP instance, therefore it executes the rule on all plugins.  These results are equivalent to running `irule` without `-r`.

**Comment by michael-conway** [comment]
If possible dump the debug logs? Yes I'll need to fire up irods 4.3

**Comment by korydraughn** [comment]
This behavior is available in iRODS v4.2.8.

**Comment by korydraughn** [comment]
Yes, I'll try and see if I can spot anything in the xml messages between the client and server.

**Comment by trel** [comment]
v4.2.8... which isn't *quite* out yet.

**Comment by michael-conway** [comment]
https://github.com/irods/irods_client_icommands/blob/master/src/irule.cpp#L178

**Comment by korydraughn** [comment]
Is there a way to set that in jargon?

**Comment by michael-conway** [comment]
FWIW I see the issue...working on a fix in IrodsRuleFactory...

**Comment by michael-conway** [comment]
Hey @korydraughn what do you think the delim format will be for input/output parms?

I'm adding a fall-thru rule translator, Jargon does parse out input/output params to support parameter overriding, e.g. in interfaces..

how would input/output parms look and be delimited in the JSON form? I'll bake that in and we should be good to go. But that's been the rub on a new format, to make a Rule 'object' for all the other sort of facilities out of the raw text..

```
 {
    "operation": "logical_quotas_start_monitoring_collection",
    "collection": "/tempZone/home/rods"
}
INPUT null
OUTPUT null
```

**Comment by korydraughn** [comment]
@jasoncoposky do you know the answer to the question above?

I'm not sure if the INPUT/OUTPUT params are supported automatically via the REPF or whether that is something that has to be implemented by the REP.

**Comment by michael-conway** [comment]
I'll just assume % for now and it may just be a non issue, it won't hold
this up...

**Comment by michael-conway** [comment]
@korydraughn I pushed a commit that I think will take care of this, or at least get us closer. I need to look at that docker build code from Terrell to be able to test against a live irods but I've been able to do some intermediate testing via junit...

**Comment by korydraughn** [comment]
Your change appears to be working. These were the only lines i changed in my test.
```java
ctx.setIrodsRuleInvocationTypeEnum(IrodsRuleInvocationTypeEnum.OTHER);
ctx.setRuleEngineSpecifier("irods_rule_engine_plugin-hard_links-instance");
```
Changing the ordering of the rule engine plugins in server_config.json did not stop it from working either. Excellent!

**Comment by michael-conway** [comment]
most excellent, thanks for your help sorting this out

**Comment by korydraughn** [comment]
is this available in a snapshot?  NFSRODS fails to compile because it cannot find the following symbol.
```java
IrodsRuleInvocationTypeEnum.OTHER
```

**Comment by michael-conway** [comment]
Yes, though if it helps I can push this to the maven repo, I bet that's
what it is...

**Comment by korydraughn** [comment]
Yes. That would help a lot.

**Comment by korydraughn** [comment]
@michael-conway has a new snapshot containing this commit been pushed to the maven repo?  im not sure if i missed it or not.  no rush either.

**Comment by michael-conway** [comment]
Yes all should be pushed, master snapshots included

**Comment by korydraughn** [comment]
awesome. thanks
