### ISSUE TITLE
4.3.1.0-RELEASE not available in maven 404

### ISSUE THREAD

**Issue by kavanLi** [DICE-UNC/jargon#360]
https://raw.github.com/DICE-UNC/DICE-Maven/master/releases response 404 : not found
So, I can not use maven version 2.2.1 to package irods-rest. Always failure.

<dependency>
            <groupId>org.irods.jargon</groupId>
            <artifactId>jargon-core</artifactId>
            <version>4.3.1.0-RELEASE</version>
</dependency>

please help.

**Comment by jakobum** [comment]
The right jargon.jar is fetched by Maven with no problems once you've added the <repository> block in your pom.xml. It also works with a local repository acting as cache so check the settings in your project.

**Comment by michael-conway** [comment]
thanks! Yes add this to your pom.xml..

```

<repositories>

<repository>

<id>dice.repository snaps</id>

<name>dice.repository.snapshots</name>

<url>https://raw.github.com/DICE-UNC/DICE-Maven/master/snapshots</url>

<releases>

<enabled>true</enabled>

</releases>

<snapshots>

<enabled>true</enabled>

<updatePolicy>always</updatePolicy>

<checksumPolicy>warn</checksumPolicy>

</snapshots>

</repository>

<repository>

<id>dice.repository</id>

<name>dice.repository</name>

<url>https://raw.github.com/DICE-UNC/DICE-Maven/master/releases</url>

<releases>

<enabled>true</enabled>

</releases>

<snapshots>

<enabled>true</enabled>

<updatePolicy>always</updatePolicy>

<checksumPolicy>warn</checksumPolicy>

</snapshots>

</repository>


</repositories>


```


I am working on moving this to github's repo service soon.

**Comment by korydraughn** [comment]
Closing.
