### ISSUE TITLE
Open type as possible contributor to NFSRODS errors not triggering replication (because of streaming)

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon#372]
possibly related to open type

see: https://github.com/irods/irods/blob/9eb6c23df45cdedff8ee9c3af71a65d304635037/server/api/src/rsModDataObjMeta.cpp#L67-L69

Link to GitHub issue https://github.com/irods/irods_client_nfsrods/issues/108

Also check irodsFileOutputStream resource directive creating via IRODSFile

**Comment by michael-conway** [comment]
see this detail: https://github.com/irods/irods_client_nfsrods/issues/108#issuecomment-743417436

**Comment by korydraughn** [comment]
This is not a Jargon issue.

The NFSRODS issue stems from POSIX tools not knowing anything about iRODS, as intended.

See https://github.com/irods/irods/issues/6142 for details.
