### ISSUE TITLE
Hooks to run Jargon tests under Jenkins

### ISSUE THREAD

**Issue by d-w-moore** [DICE-UNC/jargon#383]
To   inform (others) and remind (myself), essentially ... that I need to get this hook merged into Jargon for our Jenkins CI.

This is the dev branch where I'm working at making docker-compose configurations generally runnable under Jenkins - including (to date) Jargon, PRC and the new C++ rest client:

https://github.com/d-w-moore/irods_testing_jenkins/tree/compose_client_dot

We do this by merely inserting python script at the root level of the repository:
https://github.com/d-w-moore/jargon/commit/cde31378d

This is invasive only to the point of adding one file (the .py script) and, at repo clone and run time, adding a "command" field to the docker-compose file to avoid the huge amount of debug output spooling to the Jenkins console.  (Perhaps a setting less than DEBUG would accomplish the same thing, but I don't know log4j too well and could use a pointer there). @trel  @michael-conway 

Btw. Here's the commit where our Jenkins was first made compatible with Jargon.

https://github.com/d-w-moore/irods_testing_jenkins/commit/eff8fb44b90db4df89861e1ab8c9be9a47413ee6

**Comment by korydraughn** [comment]
Testing of Jargon is fully automated through the use of Docker. See https://github.com/DICE-UNC/jargon/blob/ec1a053c13847dca781bbf8a074d785e0eb53227/docker-test-framework/DOCKERTEST.md for details.

iRODS does not use Jenkins for testing anymore. Closing.
