### ISSUE TITLE
Helpful if a Jargon-based tools could identify itself when connecting to iRODS

### ISSUE THREAD

**Issue by tedgin** [DICE-UNC/jargon#407]
When iCommands and some other applications connect to iRODS they identify themselves by setting their name in the `options` field of the startup packet.  This allows them to be identified in the output of ips.  Jargon isn't an application, but it could provide a way for an application built using it to set the application name in the `options` field. If an application doesn't set its name Jargon could default to setting `jargon` in the `options` field. This would make it easier to understand what tools are connected to iRODS at a given instant, helping diagnose issues.

**Comment by trel** [comment]
I think there's a facility for this already...  @korydraughn ... doesn't NFSRODS do this now?

**Comment by korydraughn** [comment]
NFSRODS does not report its identity.

It also needs this feature.
