### ISSUE TITLE
Add package versions to the setup scripts in docker-test-framework

### ISSUE THREAD

**Issue by JustinKyleJames** [DICE-UNC/jargon#419]
With the latest change I made, the docker-test-framework/latest will run 4.3 as it installs the latest packages.  That is 4.3 once I updated the OS from Ubuntu 16.04 to Ubuntu 18.04.

The files in docker-test-framework/4-2 will run 4.2 but that is only because the OS is Ubuntu 16.04.

Update the setup scripts in docker-test-framework/4-2 to specify the iRODS 4.2 packages.

**Comment by korydraughn** [comment]
I think this was resolved by #426.

The docker image for 4-2 is now pinned to 4.2.12.

Closing.
