### ISSUE TITLE
Add functionality to add ADMIN_KW to ModAvuMetadataInp.java

### ISSUE THREAD

**Issue by JustinKyleJames** [DICE-UNC/jargon#420]
Add functionality to add ADMIN_KW to the ModAVUMetadataInp_PI packing instruction in ModAvuMetadataInp.java.

The key-value pair was previously added so that metadata operations work with 4.3.  This is to expand the functionality to support the ADMIN_KW.

**Comment by korydraughn** [comment]
@JustinKyleJames Please close if complete.

**Comment by korydraughn** [comment]
@JustinKyleJames ping!

**Comment by JustinKyleJames** [comment]
I don't believe that this has been implemented.  Issue #415 was addressed by modifying the packing instruction but I don't think the ADMIN_KW part has been implemented.
