### ISSUE TITLE
List content of a collection more efficiently

### ISSUE THREAD

**Issue by jjkoehorst** [DICE-UNC/jargon#427]
I am trying different approaches but I was wondering what is the most efficient way to list files **and** folders in a directory?

When using the query builder:

```
            IRODSGenQueryBuilder queryBuilder = new IRODSGenQueryBuilder(true, null);
            queryBuilder.addSelectAsGenQueryValue(COL_COLL_NAME);
            queryBuilder.addSelectAsGenQueryValue(COL_DATA_NAME);
            queryBuilder.addSelectAsGenQueryValue(COL_DATA_SIZE);
            queryBuilder.addSelectAsGenQueryValue(COL_D_MODIFY_TIME);
            queryBuilder.addConditionAsGenQueryField(COL_COLL_NAME, EQUAL, irodsPath.getParent());
```

I can't seem to find an option to select files and folders in a directory without going into the recursive path.

Also using iCommands `iquest "SELECT COLL_NAME WHERE COLL_NAME LIKE '/my/favourite/folder'"`

it will only return the folder itself not the first level of folders.

Also tried to use listFiles on the irodsFile object but is this "fast" ?

Am I missing something?

**Comment by jjkoehorst** [comment]
The `COLL_PARENT_NAME` seems to be working best at the moment, executing 2 queries to obtain the files with information and the collections.

**Comment by korydraughn** [comment]
Good.

Does that answer your question? If so, I'll close this issue.
