### ISSUE TITLE
Execute rule defined in core.re

### ISSUE THREAD

**Issue by jjkoehorst** [DICE-UNC/jargon#455]
The examples I have found in the code show how to execute a rule file or a rule string.
Is it possible to execute a rule defined in the core.re?

**Comment by luijs** [comment]
For a bit more clarity, we have a rule in core.re:
```
my_rule(){
   some actions
}
```
With icommands we can execute this rule like this:
```
irule -r irods_rule_engine_plugin-irods_rule_language-instance my_rule '*var1=/zone/home/user/dir/file.txt' ruleExecOut
```

For now we can't find the example to do the same in jargon.

**Comment by korydraughn** [comment]
Here's an example demonstrating how to call `writeLine` and extracting the values written by the server.
```java
IRODSAccount acct = IRODSAccount.instance(/* removed for brevity */);

IRODSFileSystem fsys = IRODSFileSystem.instance();
IRODSAccessObjectFactory aof = fsys.getIRODSAccessObjectFactory();

StringBuilder sb = new StringBuilder();
sb.append("main { writeLine('stdout', 'x=[*x], y=[*y]'); *y = 'updated by server'; }\n");
sb.append("INPUT *x=,*y=\n");
sb.append("OUTPUT *y, ruleExecOut");
		
List<IRODSRuleParameter> params = new ArrayList<>();
params.add(new IRODSRuleParameter("*x", "kory"));
params.add(new IRODSRuleParameter("*y", "draughn"));

RuleProcessingAO rpao = aof.getRuleProcessingAO(acct);
RuleInvocationConfiguration ctx = new RuleInvocationConfiguration();
ctx.setIrodsRuleInvocationTypeEnum(IrodsRuleInvocationTypeEnum.OTHER);
ctx.setRuleEngineSpecifier("irods_rule_engine_plugin-irods_rule_language-instance");
		
try {
    IRODSRuleExecResult execRes = rpao.executeRule(sb.toString(), params, ctx);
    System.out.println(execRes.getRuleExecOut());
    System.out.println(execRes.getRuleExecErr());
    System.out.println(execRes.getOutputParameterResults());
    System.out.println("         *y = " + execRes.getOutputParameterResults().get("*y").getResultObject());
    System.out.println("ruleExecOut = " + execRes.getOutputParameterResults().get("ruleExecOut").getResultObject());
}
finally {
    aof.closeSessionAndEatExceptions();
    fsys.closeAndEatExceptions();
}
```

**Comment by jjkoehorst** [comment]
But this “injects” the content of the rule into a call right?

rpao.executeRule(sb.toString(), params, ctx);

if an admin developed a rule and made it available through core.re how would I execute that rule without knowing the content?

**Comment by korydraughn** [comment]
> But this “injects” the content of the rule into a call right?

The example demonstrates how to call a rule defined in the server. The example just happens to use `writeLine`. You can update the contents of `main { <contents> }` to call any number of rules in core.re. For example:
```py
main { admin_approved_rule(*arg0, ..., *argN); }
```

If a rodsadmin wants to expose rules in the server to users, then they must also describe the expected inputs and outputs. iRODS doesn't provide a mechanism for users to query the contents of core.re.

> how would I execute that rule without knowing the content?

The admin must tell the user what's available. iRODS doesn't provide a mechanism for users to query the contents of core.re.

**Comment by korydraughn** [comment]
@jjkoehorst Does that answer your question?

**Comment by jjkoehorst** [comment]
I think so… will try it out asap tomorrow morning.

**Comment by korydraughn** [comment]
Sounds good.

We'll leave this open until we hear back from you.

**Comment by trel** [comment]
```
$ ierror 1102000
irods error: -1102000 NO_MICROSERVICE_FOUND_ERR
```

That error means there is no function/rule or microservice by that name and signature...

Can you execute the equivalent call to `rdm_archive_this` via `irule`?

**Comment by korydraughn** [comment]
Please show the signature of `rdm_archive_this`?

We need to see its parameter list.

**Comment by jjkoehorst** [comment]
works like a charm! was a typo 👍

**Comment by luijs** [comment]
Yep, and the signature as well:

Rule was:
```
rule_name{
logic(*argument)
}
```

and not
```
rule_name(*argument){
logic(*argument)
}
```

hence it needed to be:
```
sb.append("main { rdm_archive_this(); }\n");
...
params.add(new IRODSRuleParameter("*argument", "/unlock/home/wur.fdp/largefile"));
```

**Comment by korydraughn** [comment]
I see. Glad you got it to work.

**Comment by luijs** [comment]
Thanks for the help, sometimes the solution is obvious but you still don't see it.
