### ISSUE TITLE
RE: [iROD-Chat:12918] Move operation (Jargon)

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon#63]
I've been playing with copy and move files and collections in iRODS with Jargon. The copy operation works fine as opposed to the move operation. Let's say my iRODS file structure is:

```
/zone00
          /orion
          /temp
                 /folder1
                          file1
                 /folder2
          /aux
```

If I move "folder1" into "orion", then the structure will look like:

```
/zone00
          /orion
                 /folder1
                          file1
          /temp
                 /folder2
          /aux
```
It also works fine when I move "folder1" into "zone00":

```
/zone00
          /folder1
                   file1
          /orion
          /temp
                 /folder2
          /aux
```

However, if I try moving "folder1" back into "orion" or "temp", I get a Jargon Exception that says: `org.irods.jargon.core.exception.JargonFileOrCollAlreadyExistsException: Collection already exists`. And that's where I'm stuck. Even though "folder1" doesn't exist under "orion" anymore, Jargon still says it exists. I tried to do the same operation directly in iRODS, and it worked. But through Jargon it returns this exception.

**Comment by kellerb** [comment]
`imv` output:

```
....<MsgHeader_PI>
<type>RODS_API_REQ</type>
<msgLen>611</msgLen>
<errorLen>0</errorLen>
<bsLen>0</bsLen>
<intInfo>627</intInfo>
</MsgHeader_PI>
<DataObjCopyInp_PI>
<DataObjInp_PI>
<objPath>/tempZone/home/rods/top_dir/to_move</objPath>
<createMode>0</createMode>
<openFlags>0</openFlags>
<offset>0</offset>
<dataSize>0</dataSize>
<numThreads>0</numThreads>
<oprType>12</oprType>
<KeyValPair_PI>
<ssLen>0</ssLen>
</KeyValPair_PI>
</DataObjInp_PI>
<DataObjInp_PI>
<objPath>/tempZone/home/rods/top_dir/sibling/to_move</objPath>
<createMode>0</createMode>
<openFlags>0</openFlags>
<offset>0</offset>
<dataSize>0</dataSize>
<numThreads>0</numThreads>
<oprType>12</oprType>
<KeyValPair_PI>
<ssLen>0</ssLen>
</KeyValPair_PI>
</DataObjInp_PI>
</DataObjCopyInp_PI>
```
