### ISSUE TITLE
[iROD-Chat:13317] Jargon - PAM Authentication hanging

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon#70]
Potential PAM flush/SSL hangs in iDrop see [iROD-Chat:13317] Jargon - PAM Authentication hanging

**Comment by michael-conway** [comment]
Original report:

On the Jargon side, I set the AuthScheme on IRODSSession to PAM and added the self-signed certificate to cacerts (on the JAVA_HOME/jre/lib/security/cacerts). When I try to login (with the same user that I did the previous tests) the HTTP request for login keeps spinning (no timeout) and on the server log I got the following error:

Nov 24 10:26:13 pid:2485 NOTICE: Agent process 2786 started for puser=henrique and cuser=henrique from 127.0.0.1
Nov 24 10:26:14 pid:2485 ERROR: [-]     iRODS/server/core/src/miscServerFunct.cpp:2772:readStartupPack :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message []
        [-]     iRODS/lib/core/src/sockComm.cpp:195:readMsgHeader :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']
                [-]     libtcp.cpp:240:tcp_read_msg_header :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [read 0 expected 4]

Nov 24 10:26:14 pid:2485 ERROR: readWorkerTask - readStartupPack failed. -4000

**Comment by michael-conway** [comment]
On the logs, we can see that the SSL connection is established:

sending header: len = 139
<MsgHeader_PI>
<type>RODS_API_REPLY</type>
<msgLen>0</msgLen>
<errorLen>0</errorLen>
<bsLen>0</bsLen>
<intInfo>0</intInfo>
</MsgHeader_PI>

Jan 26 13:49:44 pid:15953 DEBUG: sslAccept: accepted SSL connection
/reslen>
</SqlResult_PI>
<SqlResult_PI>
<attriInx>0</attriInx>

**Comment by michael-conway** [comment]
Thanks for the patience, I was able to investigate this today.

Bottom line, this appears to be a potential reversion on the iRODS server behavior that requires an extra flush() statement between setting the header and sending the packing instruction.

There is, in the current Jargon master, a setting in jargon.properties


# force flushes when doing PAM auth.  This is to allow PAM to work with versions prior to iRODS 3.3, where the additional flushes
# were required.  These additional flushes cause performance issues and should not be used with iRODS 3.3
force.pam.flush=true


I have set that to true in the master.  This works, and we need to investigate on the server side. Note that this extra flush is a performance drag,so I will need to add some extra code this weekend to avoid that extra flush once the pam sequence is done.  But give this a try and we can sew this up more neatly once we're past the original issue.

**Comment by kellerb** [comment]
I think I found the cause of this in the iRODS server. https://github.com/irods/irods/issues/2527

If so, it is indeed a regression from 3.3, and the bug is present in all currently released versions of iRODS 4.x (4.0.0, 4.0.1, 4.0.2, 4.0.3).

**Comment by michael-conway** [comment]
Well done!

**Comment by michael-conway** [comment]
working on add'l fixes that can overhead iRODS and not hamstring server for extra flushes (e.g. check pi and only add flushes for certain cases)

**Comment by michael-conway** [comment]
added wrapper in code for specific calls that hang, for iRODS 4.0.x until we get to 4.1 that should handle this without setting the PAM flag.  Testing now and then will deploy
