### ISSUE TITLE
Build and Test

### ISSUE THREAD

**Issue by deardooley** [DICE-UNC/jargon#75]
I don't see the 4.x.x release anywhere in the renci maven repos. Has it been pushed somewhere? I attempted to pull and run myself, but I'm getting 179 tests failing. Probably due to not having valid test configs. Can you point me somewhere to find out what's needed to get the current release distribution? Is the jar produced from `mvn package` sufficient to use?

**Comment by michael-conway** [comment]
Sure,

Very likely you just need to do test configs.  You can build by saying

mvn install -Dmaven.test.skip=true


As an update, I'm actually running the tests now to do a 4.0.2.1 release 
candidate for Jargon.  I have it working now against 4.0.3 and just need 
to run the tests against 3.3.1.

If you can wait until later today or first thing in the AM at the latest 
that release should be available.  It has a good deal of low level fixes 
that should be useful.

MC

PS The release will be announced here:

https://github.com/DICE-UNC/jargon/releases

**Comment by deardooley** [comment]
Back burner it is. Thanks!

Rion

ps - If you’ve got a CI server hooked up, could you add the build status to the front page?

**Comment by michael-conway** [comment]
see releases for jargon...jargon 4.0.2.1-RC1 now available

**Comment by deardooley** [comment]
I guess the answer is you aren’t pushing artifacts into the renci maven server. We have plenty of resources if you need to set up a CI environment to build and test jargon. We’re already running acceptance tests against multiple versions. Testing your source wouldn’t be a significant additional load and it would help us understand where we’re at in terms of regression testing and stability during development.

Rion

**Comment by michael-conway** [comment]
Hey Rion,

The RENCI Maven Repo has sort of fallen into an indeterminate state, so 
we're pushing to GitHub as our maven repo


<repository>
             <id>dice.repository snaps</id>
             <name>dice.repository.snapshots</name>
<url>https://raw.github.com/DICE-UNC/DICE-Maven/master/snapshots</url>
             <releases>
                 <enabled>true</enabled>
             </releases>
             <snapshots>
                 <enabled>true</enabled>
                 <updatePolicy>always</updatePolicy>
                 <checksumPolicy>warn</checksumPolicy>
             </snapshots>
         </repository>
         <repository>
             <id>dice.repository</id>
             <name>dice.repository</name>
<url>https://raw.github.com/DICE-UNC/DICE-Maven/master/releases</url>
             <releases>
                 <enabled>true</enabled>
             </releases>
             <snapshots>
                 <enabled>true</enabled>
                 <updatePolicy>always</updatePolicy>
                 <checksumPolicy>warn</checksumPolicy>
             </snapshots>
         </repository>


MC
