### ISSUE TITLE
What is the progress of parallel get/put support?

### ISSUE THREAD

**Issue by deardooley** [DICE-UNC/jargon#83]
I see the code for parallel thread pooling in place now, but the jargon.properties file and javadocs say this is still an (experimental) work in progress. Dennis' ticket (https://github.com/DICE-UNC/jargon/issues/81) seems to be related to irods rather than jargon. Can you comment on the stability of this feature, whether streaming input is impacted at all when using a parallel thread pool, and the applicability in a multi-user, multi-connection environment.

**Comment by michael-conway** [comment]
Hey Rion,

I was not particularly stunned with gains on using a thread pool.  It has been tested, so I would call it 'ready' but not 'well worn' or mature.  It was meant to be an attempt at optimization, but I think the more important thing to consider is raw end-to-end transfer performance, so we're more focused on benchmarking and tuning the i/o.  Also, we're having some issues with long-running transfers on unreliable networks, and the current work is in implementing the long file restart, having jargon autonomously retry a transmission that fails for some network timeout or firewall.

**Comment by deardooley** [comment]
That would be awesome because we have been painfully aware of the random timeout issue over the last week when average file seize went over 100gb.

--
Rion

----- Reply message -----
