### ISSUE TITLE
Bogus first status callback

### ISSUE THREAD

**Issue by dkocher** [DICE-UNC/jargon#88]
The first callback on `TransferStatusCallbackListener#statusCallback` has set `bytesTransfered` set to the total length even when `totalFilesTransferredSoFar` is still `0`.

**Comment by dkocher** [comment]
This issue is not resolved in 4.0.2.1-RELEASE.

**Comment by michael-conway** [comment]
Hey david I fixed a place I found on the put...can you narrow down the type
of callback this was an issue then?

**Comment by dkocher** [comment]
I see. Looks like it is fixed for PUT but still bogus for GET. (From `DataTransferOperations#getOperation`)

**Comment by michael-conway** [comment]
OK we'll push out a little dot release after we nail down all of the 
cyberduck stuff and add that.

I want to focus on getting the performance up to snuff first.

Cheers!
MC

**Comment by dkocher** [comment]
I suppose this is now fixed with f786632153a0ae242b0bc85f0a7c622810c9ebe7.

**Comment by michael-conway** [comment]
Yes think so but of course events overtook this afternoon.  Will sew that
up and push to maven soon
