### ISSUE TITLE
Option to obtain MD5 from server after upload is complete

### ISSUE THREAD

**Issue by dkocher** [DICE-UNC/jargon#89]
It would be nice if a checksum is returned in a `PUT` operation callback listener to allow the client to compare with the checksum calculated while writing to the output stream.

**Comment by michael-conway** [comment]
I'll add an easy facility to get the MD5/Sha checksum and a nice hook to do a local versus iRODS compare.  That stuff is in there but checksums are a bit complicated, in that iRODS can specify a policy, and most servers have gone to SHA256.

working on it....

**Comment by dkocher** [comment]
Can you document how to use this with `DataTransferOperations` to get the checksum calculated by the server for uploads and downloads that would allow us to compare these with locally computed checksums.

**Comment by michael-conway** [comment]
Yes, I've also actually been working on a checksumAO with various handy
operations.  The twist is that MD5 may not be the checksum used on the
grid, we've had lots of folks discarding that for SHA256, so iRODS now has
a server side policy and some level of negotiation for checksums.

What you can do is get a hook to compare the specified checksum on the grid
with a local file, meaning the hook can find the policy, pick the algo, and
do the comparison under the covers.  Would that work w/cyberduck's approach?

**Comment by dkocher** [comment]
For our streaming implementations that we can use when #87 is resolved we update the checksum digest while reading & writing data through I/O streams. What we need is something like `ETag` returned in HTTP for the resource by the server which we can use to compare. The algorithm can be MD5, SHA1 or SHA256.

For the implementations using the `DataTransferOperations` interface get & put operations the checksum verification can be transparently handled by Jargon. We would need to read the entire stream again to compute the checksum as we let Jargon handle the file transfer by itself using a file handle.

**Comment by michael-conway** [comment]
We can wrap the put.  I can do in am.

**Comment by michael-conway** [comment]
This can work for single file calls only, what I'm working on would be a different get/put method (same params, etc) for a single file, this would return a ChecksumValue that has both the aglo and a representation of the checksum.   I'll put that into the pipeline for a coming milestone.

**Comment by michael-conway** [comment]
leave open for enhancement

**Comment by michael-conway** [comment]
you can use this service

```Java


DataObjectChecksumUtilitiesAO dataObjectChecksumUtilitiesAO = irodsFileSystem
				.getIRODSAccessObjectFactory()
				.getDataObjectChecksumUtilitiesAO(irodsAccount);
		ChecksumValue actual = dataObjectChecksumUtilitiesAO
				.retrieveExistingChecksumForDataObject(testFile
						.getAbsolutePath());


```

This will give you a CheckSum value with both the algo and stringified checksum value.  This will work when the checksum has been computed.  It is recommended to leave checksum validation turned on on JargonProperties as it is by default.  

This will be up in HEAD momentarily
