### ISSUE TITLE
Custom setting in transfer options is overridden with default from properties

### ISSUE THREAD

**Issue by dkocher** [DICE-UNC/jargon#91]
A `PUT` operation from `DataTransferOperations#putOperation` with custom value for `maxThreads` set in  `TransferOptions`. This value is overriden with the default from properties in `DataObjectAOImpl:716`.

**Comment by michael-conway** [comment]
The code at 716 is taking the TransferControlBlock passed to it and doing a copy of it to pass on to iRODS, that's simply to avoid synchronization later on.  

Further up, did change to this ~

TransferOptions myTransferOptions = new TransferOptions(
				transferControlBlock.getTransferOptions());

		if (!myTransferOptions.isUseParallelTransfer()) {
			log.info("no parallel transfer set in transferOptions");
			myTransferOptions.setMaxThreads(-1);
		}

		
		
		as that was indeed pulling from the props
		
		
		cheers
		
		mc
