### ISSUE TITLE
Provide intra file status callback

### ISSUE THREAD

**Issue by dkocher** [DICE-UNC/jargon#98]
In `TransferStatusCallbackListener` when used with `DataTransferOperations` interface.

**Comment by michael-conway** [comment]
can you clarify what this issue means?

**Comment by dkocher** [comment]
I mean to get callbacks while a single file is in transfer after each chunk written to the pipe.

**Comment by michael-conway** [comment]
I saw in SVN that jargon.props were altered to ask for status callbacks.  I did lower the interval somewhat,as Jargon accumulates callbacks and only periodically reports back.  This slightly increases overhead though.

In tests that all appears to work fine.

**Comment by dkocher** [comment]
Looks good. If callback frequency would be somewhat higher that would give a smoother progress update.

![screen shot 2015-05-07 at 11 46 51](https://cloud.githubusercontent.com/assets/71733/7512677/da9f141a-f4ae-11e4-9f2b-140db08b8dea.png)

**Comment by michael-conway** [comment]
sure, we can tweak this.

Since reports are synchronous, it adds overhead, so I'll bring it down a
few more %.  Basically it waits and discards most of the callbacks.

**Comment by dkocher** [comment]
Please reopen this issue per https://trac.cyberduck.io/ticket/8810.

**Comment by michael-conway** [comment]
looking now...will reduce the interval.  We'll need to monitor for performance hit in doing so...

**Comment by michael-conway** [comment]
I'm going to make this configurable in jargon properties. e.g.

```Java


/**
	 * Gets whether intra-file status call-backs are enabled for transfers. If
	 * <code>true</code>, and a call-back listener is provided, these allow
	 * monitoring of progress of an individual file.
	 * 
	 * @return the intraFileStatusCallbacks
	 */
	boolean isIntraFileStatusCallbacks();

	/**
	 * Gets the number of calls to ignore when jargon calls the intra-file
	 * status callback listener. No matter how many bytes have been sent, after
	 * the minimum number of calls, the callback will be made to the listener.
	 * 
	 * @return <code>int</code> with the number of callbacks.
	 */
	int getIntraFileStatusCallbacksNumberCallsInterval();


```

**Comment by michael-conway** [comment]
I've updated the callbacks to be more configurable.  You can use the settable jargon properties to get and set.

I want to keep these by default fairly large, as the callbacks are synchronous. Test suite should finish in about 15 min and I'll deploy to Maven.

```Java

	/**
	 * Gets the number of calls to ignore when jargon calls the intra-file
	 * status callback listener. No matter how many bytes have been sent, after
	 * the minimum number of calls, the callback will be made to the listener.
	 * 
	 * @return <code>int</code> with the number of callbacks.
	 */
	int getIntraFileStatusCallbacksNumberCallsInterval();

	/**
	 * Gets the number of bytes to ignore until jargon calls the intra-file
	 * status callback listener. No matter how many times the listener has been
	 * called, after the minimum number of bytes, the callback will be made to
	 * the listener.
	 * 
	 * @return <code>long</code> with the number of bytes between a callback
	 */
	long getIntraFileStatusCallbacksTotalBytesInterval();



```

**Comment by dkocher** [comment]
The synchronous nature of these callbacks is not an issue as the actual update of the user interface is decoupled.
