### ISSUE TITLE
Option to read with offset using DataTransferOperations

### ISSUE THREAD

**Issue by dkocher** [DICE-UNC/jargon#99]
When using `IRODSFileInputStream` you can seek to a position in the file to resume an interrupted transfer. With `DataTransferOperations` there is no option to read and write with an offset to the target file.

**Comment by michael-conway** [comment]
restart of interrupted transfers is under https://github.com/DICE-UNC/jargon/issues/5

Put restarts are in 4.0.2.1 get will be in 4.0.2.2.
